# Generated by Django 5.1.5 on 2025-02-11 13:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_banking", "0003_alter_bankaccount_account_type_wallet"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recipiant_address",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Wallet", "Wallet"),
                            ("Bank Account", "Bank Account"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "transaction_category",
                    models.CharField(
                        blank=True,
                        choices=[("Deposit", "Deposit"), ("Withdrawal", "Waithdrawal")],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "transaction_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Pending", "Pending"),
                            ("Completed", "Completed"),
                            ("Failed", "Failed"),
                        ],
                        default="Pending",
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "receipt",
                    models.CharField(editable=False, max_length=10, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recipiant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender_bank_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core_banking.bankaccount",
                    ),
                ),
            ],
        ),
    ]
