# Generated by Django 5.1.5 on 2025-02-11 14:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core_banking", "0004_transaction"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="recipiant",
            new_name="recipient",
        ),
        migrations.RenameField(
            model_name="transaction",
            old_name="recipiant_address",
            new_name="recipient_address",
        ),
    ]
