# Generated by Django 5.1.5 on 2025-02-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_banking", "0005_rename_recipiant_transaction_recipient_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wallet",
            name="created_at",
        ),
        migrations.AddField(
            model_name="wallet",
            name="last_update",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
